export const CREATE_QUIZ_QUESTION = "CREATE_QUIZ_QUESTION"
export const FINISH_CREATE_QUIZ_START = "FINISH_CREATE_QUIZ_START"
export const FINISH_CREATE_QUIZ_ERROR = "FINISH_CREATE_QUIZ_ERROR"
export const FINISH_CREATE_QUIZ_SUCCESS = "FINISH_CREATE_QUIZ_SUCCESS"